# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-08 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191108_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date(2019, 11, 8)),
        ),
    ]
